env_module: "policy.envs.sampletask_env:SampleTaskEnv"
env_name: "SampleTaskEnv"
num_parallel: 512
num_parallel_test: 1
max_timestep: 1000
frame_skip: 1

action_scale: 1.0 #0.95 during training
random_scale: 1.0
#text: ['sidestep', 'forward', 'backward', 'stand still',',']
num_candidate: 10

action_rgr_step: [4,3]
action_mode: 'full' #epsilon, locomotion
action_step: [39,38,36,34,32,28,25,20,18,15,12,10,8,6,5,4,3]

test_action_scale: 1.0
test_random_scale: 0.0